name: "action to create or use an existing workspace for aml"
description: "read previously added file in by the action"
author: "ashishonce"
inputs:
  subscriptionId:
    description: "your azure subscription id"
    required: true
    default: ""
branding:
  icon: chevron-up
  color: 'green'
runs:
  using: "docker"
  image: "Dockerfile"