name: "action to create or use an existing workspace for aml"
description: "read previously added file in by the action"
author: "ashishonce"
inputs:
  azureCredentials:
    description: "azure credentials"
    required: true
  workspaceName:
    description: " name of the workspace to use"
    required: true
  createWorkSpace:
    description: "if workspace doesn't exist , this will create it"
  computeTarget:
    description: " name of compute cluster to use"
  experimentName:
    description: "name of the experiment, it will be used to refer to an existing experiment or create a new one":
    required: true
branding:
  icon: chevron-up
  color: 'green'
runs:
  using: "docker"
  image: "Dockerfile"