name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@master
      
      - name: Azure Login
        id: azure_login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Self test
        id: selftest
        uses: ashishonce/amlworkspace@master
        with:
          azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
          workspaceName: "ashkumadevtestwkrspace1"
          createWorkSpace : true
          computeTarget : "cpu-cluster"